micronaut:
  application:
    name: account

endpoints:
  health:
    enabled: true

datasources:
  default:
    url: jdbc:h2:mem:account_db
    username: sa
    password: ""
    driverClassName: org.h2.Driver

flyway:
  datasources:
    default:
      locations: classpath:migrations