micronaut:
  application:
    name: account

endpoints:
  health:
    enabled: true

datasources:
  default:
    url: jdbc:h2:mem:account_db;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
    driverClassName: org.h2.Driver

flyway:
  datasources:
    default:
      locations: classpath:db/migration

jackson:
  serialization:
    writeDatesAsTimestamps: false